In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, LabelEncoder

In [14]:
df= pd.read_csv("HousingData.csv")
df.sample(10)
print(df.isnull().sum())
df['CRIM'] = df['CRIM'].fillna(df['CRIM'].median())
df['ZN'] = df['ZN'].fillna(df['ZN'].median())
df['INDUS'] = df['INDUS'].fillna(df['INDUS'].median())
df['CHAS'] = df['CHAS'].fillna(df['CHAS'].median())
df['AGE'] = df['AGE'].fillna(df['AGE'].median())
df['LSTAT'] = df['LSTAT'].fillna(df['LSTAT'].median())
print(df.isnull().sum())
df.sample(10)

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64
CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
243,0.12757,30.0,4.93,0.0,0.428,6.393,7.8,7.0355,6,300,16.6,374.71,5.19,23.7
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4,307,21.0,376.88,14.81,16.6
242,0.10290,30.0,4.93,0.0,0.428,6.358,52.9,7.0355,6,300,16.6,372.75,11.22,22.2
108,0.12802,0.0,8.56,0.0,0.520,6.474,97.1,2.4329,5,384,20.9,395.24,12.27,19.8
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9
151,1.49632,0.0,19.58,0.0,0.871,5.404,100.0,1.5916,5,403,14.7,341.60,13.28,19.6
164,2.24236,0.0,19.58,0.0,0.605,5.854,91.8,2.4220,5,403,14.7,395.11,11.64,22.7
313,0.26938,0.0,9.90,0.0,0.544,6.266,82.8,3.2628,4,304,18.4,393.39,7.90,21.6
82,0.03659,25.0,4.86,0.0,0.426,6.302,32.2,5.4007,4,281,19.0,396.90,6.72,24.8
471,4.03841,0.0,18.10,0.0,0.532,6.229,90.7,3.0993,24,666,20.2,395.33,12.87,19.6

In [15]:
Q1 = df['MEDV'].quantile(0.25)
Q3 = df['MEDV'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['MEDV'] = np.where(df['MEDV'] < lower, lower, np.where(df['MEDV'] > upper, upper, df['MEDV']))
print(df['MEDV'].describe())

count    506.000000
mean      21.877075
std        7.602976
min        5.062500
25%       17.025000
50%       21.200000
75%       25.000000
max       36.962500
Name: MEDV, dtype: float64

In [16]:
df1 = pd.read_csv("Titanic-Dataset.csv")
df1['Age'] = df1['Age'].fillna(df1['Age'].median())

minmax_scaler = MinMaxScaler()
df1['Age_MinMax'] = minmax_scaler.fit_transform(df1[['Age']])

std_scaler = StandardScaler()
df1['Age_Standard'] = std_scaler.fit_transform(df1[['Age']])

print(df1[['Age', 'Age_MinMax', 'Age_Standard']].head())

    Age  Age_MinMax  Age_Standard
0  22.0    0.271174     -0.565736
1  38.0    0.472229      0.663861
2  26.0    0.321438     -0.258337
3  35.0    0.434531      0.433312
4  35.0    0.434531      0.433312

In [17]:
iris = pd.read_csv("csv_data_iris.csv")

l= LabelEncoder()
iris['cat'] = l.fit_transform(iris['class'])

ohe = OneHotEncoder(sparse_output=False)
ohe_array = ohe.fit_transform(iris[['class']])
print(ohe_array)
iris.sample(10)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class,cat
17,5.1,3.5,1.4,0.3,setosa,0
107,7.3,2.9,6.3,1.8,virginica,2
31,5.4,3.4,1.5,0.4,setosa,0
61,5.9,3.0,4.2,1.5,versicolor,1
102,7.1,3.0,5.9,2.1,virginica,2
118,7.7,2.6,6.9,2.3,virginica,2
57,4.9,2.4,3.3,1.0,versicolor,1
129,7.2,3.0,5.8,1.6,virginica,2
35,5.0,3.2,1.2,0.2,setosa,0
22,4.6,3.6,1.0,0.2,setosa,0

In [18]:
print(df1['Survived'].value_counts())

from sklearn.utils import resample

died = df1[df1['Survived'] == 0]
survived = df1[df1['Survived'] == 1]
survived_upsampled = resample(survived, replace=True, n_samples=len(died), random_state=42)
df1_balanced = pd.concat([died, survived_upsampled])


print(df1_balanced['Survived'].value_counts())

Survived
0    549
1    342
Name: count, dtype: int64
Survived
0    549
1    549
Name: count, dtype: int64